dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    optimizer:
      enabled: true
      runs: 800
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
dotenv: .env
networks:
  default: development
  kovan: active
wallets:
  from_key: ${PRIVATE_KEY}
